FROM quay.io/jupyter/minimal-notebook:2024-07-22

LABEL maintainer="Marco Willi <marco.willi@fhnw.ch>"
LABEL description="ML Template Repo"

USER root

RUN apt-get update && \
    apt-get install -y  \
        make && \
    apt-get clean

USER $NB_UID

WORKDIR /workspace/code

COPY environment.yaml .

RUN mamba env update -n base --file environment.yaml && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

EXPOSE 8886
