paths:
  data_root_path: ${oc.env:DATA_PATH,/workspace/data}
  code_root_path: ${oc.env:CODE_PATH,/workspace/code}
  log_path: /workspace/code/logs

debug: False

defaults:
  - _self_
  - experiment: null
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

timestamp: ${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${paths.log_path}/${hydra.job.name}/${experiment.id}_${timestamp}

wandb:
  project: "my_project"
  entity: "my_user_name"
  enable: True
  run_id: ${experiment.id}_${timestamp}
